### ISSUE TITLE
Feature request - promote search section above volume list at https://oldinsurancemaps.net/loc/volumes/

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#11]
As more volumes are loaded, users will need to scroll further and further down https://oldinsurancemaps.net/loc/volumes/ to find the search section for finding specific loaded volumes or just to load new volumes. With 36/267 volumes loaded, I need to scroll down two full screen lengths, increasing to 15 screen lengths as more volumes will be loaded. Even then, the list only reflects loaded volumes so the user may still need to use the search section. That's also the area where the user can see what communities are even available. Maybe they wanted to look into a community that wasn't even available so now they're disgruntled after all the scrolling.

Thus, moving the search section above the volume list is a significant user experience improvement since the user can see what's available, what's loaded, and what's not loaded in a single spot that doesn't move over time. If they want to scroll through the loaded volume list, that'd still be available beneath the search section so no harm's done.

**Comment by mradamcox** [comment]
So one thing I did recently is add the volume search bar into the home page as well. Do you think that does enough to make search easier? Perhaps moving it to the top of the volumes page as a hidden and expandable section would be the best?

**Comment by BNAndras** [comment]
The other sections under Content (Document, Layers, and Web Maps) all have the search functionality at the top of the page. So volumes should have something similar at the top. A collapsible section would be fine.

**Comment by mradamcox** [comment]
This will actually require a little refactoring of the search component so I'm going to move it off this milestone.
