### ISSUE TITLE
Missing thumbnail in Abbeville, LA. 1889 volume

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#28]
https://oldinsurancemaps.net/documents/1139 has a placeholder "no image" icon in https://oldinsurancemaps.net/loc/sanborn03264_002/, which appeared after the page was georeferenced.

**Comment by BNAndras** [comment]
The image icon now appears. I've georeferenced several sheets so far, and that was the first time I saw the placeholder. I'm guessing the thumbnail creation was lagging behind the actual georeferencing since I could see the sheet just fine on its document page.

Do we need to update the thumbnails at all? Would it be easier to use the same thumbnail from when the sheet goes through the splitting process? Currently, if you undo the georeferencing, the system discards the georeferenced thumbnail, creates a new thumbnail, and then discards that thumbnail when you redo the georeferencing.

**Comment by mradamcox** [comment]
Yeah, thumbnail creation runs in the background, so sometimes the placeholder appears for a short time before.

Are you talking about updating the thumbnail on the layer? I think that's a good thing to retain. For example, a thumbnail like this
![image](https://user-images.githubusercontent.com/10427268/154989630-9cc6563a-62b4-4703-8bac-f39ba501a210.png)
indicates that the georeferencing needs to be redone, and after it's redone, it will look better. That said, I'm not sure I understand your last scenario 100% so I may be missing your point...
