### ISSUE TITLE
User invite message typo

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#32]
I noticed a typo when you successfully invite users by email address: "Invitations succefully sent to 'hatac41540@naluzotan.com'". Unfortunately, this appears to be an issue upstream since I see 45 hits for "succefully" in https://github.com/GeoNode/geonode/search?q=succefully.

**Comment by mradamcox** [comment]
This would be upstream in geonode.

**Comment by BNAndras** [comment]
I'll make a PR upstream.
