### ISSUE TITLE
Volume page broken after splitting a sheet already split

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#37]
I broke the Arcadia volume at https://oldinsurancemaps.net/loc/sanborn03270_002/. This time, I split one of the sheets and I was going back to the volume page with my browser's back button. I noticed the split lines were still available so I went forward in my browser history. Here, I tried the splitting process again (figuring either nothing happens or maybe we get duplicate sections). All I got was the generic Geonode error page. After that, I couldn't load the volume. It was still available when I went back after the original split.

**Comment by mradamcox** [comment]
The strategy thus far has been obfuscation: hiding the preparation link if the document has already been prepared. So, this use of the back button breaks that (flimsy) plan, and must be addressed. Ultimately it will be handled through #22.
