### ISSUE TITLE
[Bug] https://oldinsurancemaps.net/account/password/reset/

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#38]
**Describe the problem**
When resetting a password, https://oldinsurancemaps.net/account/password/reset/ includes a reference to the placeholder text of "admin@example.com".

**Expected behavior**
The email address should be the current admin's email address.

**To Reproduce**
1. Open https://oldinsurancemaps.net/account/password/reset/ and scroll to bottom

**Environment info:**
 - Device: iPhone 8/Mac Mini/PC
 - Operating System: Windows/MacOS
 - Browser: Firefox/Safari/Chrome

**Comment by mradamcox** [comment]
Will fix very soon. This is pulled from the `THEME_ACCOUNT_CONTACT_EMAIL` setting.
