### ISSUE TITLE
[Bug] Blurry layer image exports

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#45]
**Describe the problem**
The JPEG/PDF/PNG exports for georeferenced layers are blurry. It seems the images are downsampled to a few hundred pixels in either dimension

**Environment info:**
 - Device: Mac mini
 - Operating System: MacOS
 - Browser: Safari

**Additional context**
[geonode-lake_charles_la_1909_p28.pdf](https://github.com/mradamcox/loc-insurancemaps/files/8145914/geonode-lake_charles_la_1909_p28.pdf)
[geonode-eunice_la_1950_p1.pdf](https://github.com/mradamcox/loc-insurancemaps/files/8145917/geonode-eunice_la_1950_p1.pdf)

**Comment by mradamcox** [comment]
Will need to look into this at the same time as #46.

**Comment by BNAndras** [comment]
I'm fairly sure the image formats are lower resolution thumbnails. They're available for vector layers as well (see https://geonode.cloudtostreet.info/layers/geonode_data:geonode:tjk_hot_roads). If it's trivial to disable their download, that'd be the best so people don't grab the wrong data and get disappointed.
