### ISSUE TITLE
[Request] Additional sorts in search interface

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#47]
**Describe the feature or enhancement you're looking for**
At https://oldinsurancemaps.net/layers/ & https://oldinsurancemaps.net/documents/, the most recent and least recent sorts use the sheet's publication date. I'd like to include a sort by modification date and time.  That's not currently exposed elsewhere in the user interface, and it would be useful for finding recent activity or a sheet prepared a while ago that hadn't been georeferenced yet.

**Comment by mradamcox** [comment]
These pages and the search management is straight from upstream GeoNode, so I don't think it would be trivial to add these properties to the index, though this is a good idea.

To your last point, you can filter by the Georeferencing Status keyword 'prepared' to only see those documents.

**Comment by BNAndras** [comment]
Yeah, I was using the status keyword in that scenario, but without the modification time sorts, that particular workflow is untenable.

**Comment by mradamcox** [comment]
I'm going to close this now, as #99 will be moving away from GeoNode, and Document and Layer searching outside of the volume summaries is not a high priority at the moment. Re-introducing these search pages may come down the road, however.
