### ISSUE TITLE
[Bug] Volume map overview doesn't fully load after trimming key map layer

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#56]
**Describe the problem**
I georeferenced the key map for Kinder, LA 1921. It was available in the volume overview map so  I set it as the key layer. I then trimmed the key map and went back to the volume overview. The map viewer won't fully load as seen in the attached screenshot. If I unset the key map, the map viewer won't load. If I remove the mask, the map viewer still won't load.

**Environment info:**
 - Device: Laptop
 - Operating System: Ubuntu 20.04 LTS
 - Browser: Firefox 97.0

**Additional context**
![image](https://user-images.githubusercontent.com/20251272/156904565-164e6727-d49a-43ef-a7d5-b15158ba3a41.png)

**Comment by BNAndras** [comment]
Georeferencing an additional document allows the map viewer to fully initialize but at the incorrect extent and scale referenced in https://github.com/mradamcox/loc-insurancemaps/issues/54

**Comment by mradamcox** [comment]
May be connected to #5 as well

**Comment by mradamcox** [comment]
Disregard my comment above, this is the same as #54, fixed by refreshing the layer_lookup on this volume. Closing so the other ticket can stay open.
