### ISSUE TITLE
Using Global or Louisiana regions in search causes errors

### ISSUE THREAD

**Issue by mradamcox** [mradamcox/loc-insurancemaps#6]
Using `Global` region in search (or `Louisiana`) clicked through from document detail causes empty results, and a `NaN` error in the listing.

![image](https://user-images.githubusercontent.com/10427268/153098574-86f4ccff-3a0a-422d-ab3d-0662a329b7ec.png)

**Comment by BNAndras** [comment]
https://oldinsurancemaps.net/search/?regions__name__in=Louisiana and https://oldinsurancemaps.net/search/?regions__name__in=Global currently return 377 documents across 19 pages on desktop Safari.

**Comment by BNAndras** [comment]
I suggest this issue be closed. I haven't been able to replicate the issue in further testing.

**Comment by mradamcox** [comment]
Yeah, tried it yesterday too and it seemed ok. I'll close for now. The Global region is a little strange because it is not explicitly loaded [like all the others](https://github.com/mradamcox/loc-insurancemaps/blob/main/loc_insurancemaps/fixtures/la-regions.json). So, it would still be good to look a little further into it, but doesn't seem pressing.
