### ISSUE TITLE
[Bug] Truncated volume name in tabs on initial load

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#64]
**Describe the problem**
I loaded https://oldinsurancemaps.net/layers/geonode:new_orleans_la_1893_vol_4_pa and https://oldinsurancemaps.net/layers/geonode:new_orleans_la_1893_vol_4_pb. On initial load, the Safari tabs said "Orleans, La. | 1887 | Vol. 4 pA - LaHMG" and "Orleans, La. | 1887 | Vol. 4 pB - LaHMG". After I refreshed, the tabs say "New Orleans, La." instead of "Orleans, La." Upon subsequent refreshes, the tabs are still showing "New Orleans, La." I had georeferenced those two layers in Chrome and not Safari so this wouldn't be Safari just working off a stale cache.

**Environment info:**
 - Device: Mac mini M1
 - Operating System: macOS Monterey 
 - Browser [e.g. Firefox, Safari]

**Comment by mradamcox** [comment]
I'm not sure exactly what you mean by load in this case... How did you access these pages and see the incomplete tab title? I'm I'm inclined to close this soon because it seems like a real edge case and its effect on the overall app is very small.

**Comment by BNAndras** [comment]
I opened the pages from the volume page. I’ve noticed this issue intermittently from the beginning, and this doesn’t need an immediate fix at all. I logged this bug in the system in case it’s related to something else under the hood.

**Comment by mradamcox** [comment]
Ok, sounds good, we'll track it for a while then.

**Comment by mradamcox** [comment]
I just poked around a little on this, and sounds like it may be a Safari tab title optimization. Here's a very old thread about it, https://bugzilla.mozilla.org/show_bug.cgi?id=278893, but if this is still a feature in Safari then maybe that's what's going on. Going to close this ticket for now.
