### ISSUE TITLE
[Bug] Inconsistent column sorting in volume list

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#71]
**Describe the problem**
On https://oldinsurancemaps.net/loc/volumes/, the user can click the column heading to sort the volume list by that column's values (first click is for ascending order, second for descending). Clicking the Loaded by heading unexpectedly sorts the volume list by the Community column values. Clicking the Loaded by column heading again doesn't change the sorting list. 

**Expected behavior**
Clicking the Loaded by heading should sort the volume list by user names in ascending order. A second click on the heading should reverse that sorted order.

**Environment info:**
 - Device: iPhone 8 & Mac mini M1
 - Operating System: iOS 15.4 & macOS 12.2 Monterey
 - Browser: Safari 15.4 & Chrome 99.0.4844.51

**Comment by mradamcox** [comment]
Good catch. Seems the sort doesn't work on a subproperty of the object:
```<th data-sort="loaded_by.name" style="text-align:center;">Loaded by</th>```
Will have to reserialize the content so that loaded_by name is a top level property.
