### ISSUE TITLE
[Bug] Map viewer doesn't go full-screen in Safari

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#72]
**Describe the problem**
In Chrome, going full-screen with the map viewer fills the entire screen. In Safari, going full-screen fills the screen width-wise but doesn't fill the entire screen. 

**Environment info:**
 - Device: Mac mini M1
 - Operating System: macOS 12.2 Monterey
 - Browser: Safari 15.3

**Additional context**
Chrome
![Screen Shot 2022-03-15 at 15 51 15 PM](https://user-images.githubusercontent.com/20251272/158485427-258a60d1-b528-40dd-a174-e88b24cc0ebd.jpg)
Safari
![Screen Shot 2022-03-15 at 15 51 25 PM](https://user-images.githubusercontent.com/20251272/158485432-44ad90f0-4a54-49bf-b891-b376e8606582.jpg)

**Comment by mradamcox** [comment]
Closing in favor of #58, which will be a better place to track the safari fullscreen woes.
