### ISSUE TITLE
[Bug] Off-center login/logout message icon

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#74]
**Describe the problem**
When logging in and out, the message at the bottom of the screen has an off-center white cross at the right side

**Expected behavior**
This symbol should be centered vertically with the message like previously. I believe the color used to be black, but don't quote me on that.

**Environment info:**
 - Device: Mac mini M1
 - Operating System: MacOS 12.3 Monterey
 - Browser: Safari 15.3 and Chrome 99

**Additional context**
![Message Box](https://user-images.githubusercontent.com/20251272/159135224-5e9f2755-cdb5-4006-bd17-63afe09f244e.jpg)

**Comment by mradamcox** [comment]
Oh interesting, yeah, the style on the close button on the new modals in the volume summary (map key and enlarged document images) has overwritten this style. Should be a pretty easy thing to fix...
