### ISSUE TITLE
[Bug] (old) Homepage SVG icons don't render on iOS

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#76]
**Describe the problem**
Section headings on the home page are off-center on smaller screens. It seems the labels are padded with extra spaces on the left compared to the right.

**Environment info:**
 - Device: iPhone 8
 - Operating System: iOS 15.3
 - Browser: Safari & Firefox

**Additional context**
![F50ADB38-1792-4255-B40F-541EA758170B](https://user-images.githubusercontent.com/20251272/159141659-8b1166aa-b61b-4b78-bf75-990150f2593c.png)

**Comment by mradamcox** [comment]
There are actually icons to the left of those headers that aren't showing up apparently. They do on android for me on Firefox & Chrome, so I'm guessing this is an iOS thing.

**Comment by mradamcox** [comment]
I have reintroduced these icon classes in a new context and @BNAndras has confirmed they do appear on iOS now. Closing ticket.
