### ISSUE TITLE
[Bug] Missing volume repair tool

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#77]
**Describe the problem**
On iOS Firefox, only the refresh tool is visible by the georeferencing overview. In Safari and Chrome, both the refresh and the wrench tools are available.

**Additional context**
![D6B83388-A6FB-47CC-8245-5A5CC6B4047B](https://user-images.githubusercontent.com/20251272/159142045-fe42165f-015f-4f59-821b-e5dfdbf408e8.png)

**Comment by mradamcox** [comment]
Can you confirm that you are signed in? It shows up for in Firefox when signed in.

**Comment by BNAndras** [comment]
Oops, never mind. I’m closing the issue.
